FROM logstash:5

# Copy logstash config files into logstash config dir in the container
COPY config/* /etc/logstash/conf.d/

# Add logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json 
